services:
  db:
    image: gvenzl/oracle-xe:18-slim
    container_name: oracle-xe
    restart: unless-stopped
    environment:
      ORACLE_PASSWORD: "newdatabase"
      ORACLE_CHARACTERSET: "AL32UTF8"
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

  backend:
    build: ./backend/employee_management
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: newdatabase
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  oracle-data:
