package com.example.employee_management.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "HR_LEAVE_SCHEDULE") // Make sure this matches your actual table name
public class LeaveSchedule {

    @Id
    @Column(name = "ID")
    // Assuming ID is not auto-generated by a sequence for this table based on schema.
    // If it is, add @GeneratedValue and @SequenceGenerator like your other entities.
    private Long id;

    @Column(name = "LEAVE_YEAR_ID")
    private Long leaveYearId;

    @Column(name = "EMPLOYEE_ID", length = 20) // Matches VARCHAR2(20 BYTE)
    private String employeeId; // This will store the business key like "20004588"

    @Column(name = "STATUS", length = 25)
    private String status;

    @Column(name = "DESCRIPTION", length = 255)
    private String description;

    // Constructors
    public LeaveSchedule() {
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getLeaveYearId() {
        return leaveYearId;
    }

    public void setLeaveYearId(Long leaveYearId) {
        this.leaveYearId = leaveYearId;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}